### ISSUE TITLE
Lỗi - TRÀ CÚ - KHÔNG XÁC ĐỊNH ĐƯỢC ƯU TIÊN LẦN KHÁM TRƯỚC VỚI THẺ LẤY THEO MÃ BHXH

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dh.ordinal#2]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN TRÀ CÚ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbtracu_062024052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/CF6oL9JIv)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Các thẻ có định dạng quét lấy mã BHXH sẽ không lấy được thông tin lần khám trước để xác định ưu tiên cho BN khi bắt STT lần sau :
> Đã test trên phiên bản 24/06

![image](https://github.com/dh-hos/dh.ordinal/assets/130281806/17906652-87bf-4e66-8975-f8bdd31abbce)

mã thẻ test :

8421859132|4b696d205468e1bb8b204b696d20486f61|01/01/1967|2|-|84 - 027|13/05/2023|-|22/05/2023|84078421859132|-|4| 01/07/2022|56d86d65dfdab81c-1202|4|487579e1bb876e205472c3a02043c3ba2c2054e1bb896e68205472c3a02056696e68|$

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 RegisterOrdinal.exe v.1.24.0625.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12406250-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12406250-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FRegisterOrdinalexe%2F12406250-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - TRÀ CÚ - KHÔNG XÁC ĐỊNH ĐƯỢC ƯU TIÊN LẦN KHÁM TRƯỚC VỚI THẺ LẤY THEO MÃ BHXH

- ☑: https://github.com/dh-hos/dh.ordinal/issues/2

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/RegisterOrdinal.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
Đã test lại các loại được ưu tiên
đã Fix thẻ BHYT dùng mã BHXH xác định ưu tiên đúng mã thẻ
test trên mã thẻ :

2024018139 - 21 tháng - TE1848422641683 - thẻ BHYT - ưu tiên tuổi
8422641683|5468e1baa16368205468e1bb8b204368616e65204d6f6e69|20/09/2022|2|-|84 - 029|20/09/2022|-|10/10/2022|84088422641683|-|4| 20/09/2027|46c58f59716e7bac-7102|1|487579e1bb876e20447579c3aa6e2048e1baa3692c2054e1bb896e68205472c3a02056696e68|$


2024019131 - thẻ BHYT - ưu tiên lần khám trước
DN4928422467471|4cc3aa205175e1bb9163205468e1bb916e67|29/11/1997|1|4b68c3b36d20312c205068c6b0e1bb9d6e6720312c205468e1bb8b2078c3a320447579c3aa6e2048e1baa3692c2054e1bb896e68205472c3a02056696e68|92 - 001|01/01/2022|-|11/01/2022|92018422467471|-|4|01/07/2024|4aac0e714dde47d1-1202|$


2024000636 - 57t - GD4848421859132 - thẻ BHYT  - ưu tiên lần khám trước
8421859132|4b696d205468e1bb8b204b696d20486f61|01/01/1967|2|-|84 - 027|13/05/2023|-|22/05/2023|84078421859132|-|4| 01/07/2022|56d86d65dfdab81c-1202|4|487579e1bb876e205472c3a02043c3ba2c2054e1bb896e68205472c3a02056696e68|$


2024019132 - 37t - DN4929210020211 - thẻ CCCD  - ưu tiên lần khám trước
089087022134|351767084|Hà Văn Tuấn|02101987|Nam|Ấp Trung, Mỹ Hiệp, Chợ Mới, An Giang|12112022
![image](https://github.com/dh-hos/dh.ordinal/assets/130281806/512355b8-a2ff-4045-b554-17d209d85741)
