### ISSUE TITLE
Lỗi - QUÉT CCCD KHÔNG NHẬN PHÍM ENTER

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dh.ordinal#3]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN TRÀ CÚ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbtracu_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/2U65whkIp)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Test theo qui trình thì khi quét thẻ BHYT vẫn in ra số thứ tự, riêng thẻ CCCD thì khi quét phải bấm phím Enter vật lý mới in được STT
- Đã cho quét lại option add Enter key cho máy quét theo hưỡng dẫn : Trang 88
[ds9308_doc_setup.pdf](https://github.com/user-attachments/files/17274352/ds9308_doc_setup.pdf)
- Quét thử trên file text thì con trỏ vẫn nhận phím Enter xuống dòng ( quét vài lần cũng có khi không xuống)
- Quét trên Ordinal thì hoàn toàn không nhận phím Enter.
 [Clip test](https://gofile.me/78TQg/g2D4i3gjx) trực tiếp tại Kiosk 
✴️ Đề nghị fix hoặc điều chỉnh code để xử lý vấn đề trên để nghiệm thu hệ thống.

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận**
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-10-09.

**Comment by nqhoa1005** [comment]
✔️ **ĐÃ TIẾP NHẬN PHIÊN BẢN MỚI** 
👉 **Vui lòng chờ phối hợp với đơn vị test lại**

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
- Đã xử lý và xác nhận với đơn vị
![image](https://github.com/user-attachments/assets/a9860ed2-600d-4b6f-8cb0-69b985ec2bb1)


---
✳️ Lần test :
